version: '3'

services: 

    notebook:
        image: jupyter/pyspark-notebook:latest
        ports: 
            - 8888:8888
        volumes: 
            - ./data:/home/jovyan/data
            - ./results:/home/jovyan/results
            - ./:/home/jovyan/